package wang.wangxinarhat.dao;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT. Enable "keep" sections if you want to edit. 
/**
 * Entity mapped to table "CITY_INFO".
 */
public class CityInfo {

    private Long id;
    /** Not-null value. */
    private String city_id;
    private String city_spell_zh;
    private String city_area;
    private String city_town;
    private String city_province;

    public CityInfo() {
    }

    public CityInfo(Long id) {
        this.id = id;
    }

    public CityInfo(Long id, String city_id, String city_spell_zh, String city_area, String city_town, String city_province) {
        this.id = id;
        this.city_id = city_id;
        this.city_spell_zh = city_spell_zh;
        this.city_area = city_area;
        this.city_town = city_town;
        this.city_province = city_province;
    }

    public Long getId() {
        return id;
    }

    public void setId(Long id) {
        this.id = id;
    }

    /** Not-null value. */
    public String getCity_id() {
        return city_id;
    }

    /** Not-null value; ensure this value is available before it is saved to the database. */
    public void setCity_id(String city_id) {
        this.city_id = city_id;
    }

    public String getCity_spell_zh() {
        return city_spell_zh;
    }

    public void setCity_spell_zh(String city_spell_zh) {
        this.city_spell_zh = city_spell_zh;
    }

    public String getCity_area() {
        return city_area;
    }

    public void setCity_area(String city_area) {
        this.city_area = city_area;
    }

    public String getCity_town() {
        return city_town;
    }

    public void setCity_town(String city_town) {
        this.city_town = city_town;
    }

    public String getCity_province() {
        return city_province;
    }

    public void setCity_province(String city_province) {
        this.city_province = city_province;
    }

}
