package wang.wangxinarhat.dao;

import android.database.sqlite.SQLiteDatabase;

import java.util.Map;

import de.greenrobot.dao.AbstractDao;
import de.greenrobot.dao.AbstractDaoSession;
import de.greenrobot.dao.identityscope.IdentityScopeType;
import de.greenrobot.dao.internal.DaoConfig;

import wang.wangxinarhat.dao.CityInfo;

import wang.wangxinarhat.dao.CityInfoDao;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT.

/**
 * {@inheritDoc}
 * 
 * @see de.greenrobot.dao.AbstractDaoSession
 */
public class DaoSession extends AbstractDaoSession {

    private final DaoConfig cityInfoDaoConfig;

    private final CityInfoDao cityInfoDao;

    public DaoSession(SQLiteDatabase db, IdentityScopeType type, Map<Class<? extends AbstractDao<?, ?>>, DaoConfig>
            daoConfigMap) {
        super(db);

        cityInfoDaoConfig = daoConfigMap.get(CityInfoDao.class).clone();
        cityInfoDaoConfig.initIdentityScope(type);

        cityInfoDao = new CityInfoDao(cityInfoDaoConfig, this);

        registerDao(CityInfo.class, cityInfoDao);
    }
    
    public void clear() {
        cityInfoDaoConfig.getIdentityScope().clear();
    }

    public CityInfoDao getCityInfoDao() {
        return cityInfoDao;
    }

}
